stages:
  - build
  - test
  - benchmark
  - benchmark-completion

.scripts:
   prep-path: &PREP_PATH |
     export PROJECT_FOLDER=$(pwd)
     export PATH=${PROJECT_FOLDER}/bin:${PATH}

   ensure-git-dependencies: &GIT_DEPS |
     git -C ../graal fetch --all || true
     git -C ../mx pull || true
     git clone --depth=1 https://github.com/smarr/truffleruby-faststart.git faststart || true
     rm -Rf faststart/.git || true
  
   ensure-faststart: &GIT_FASTSTART |
     git clone --depth=1 https://github.com/smarr/truffleruby-faststart.git faststart || true
     rm -Rf faststart/.git || true

   package-truffleruby: &PACKAGE_TR |
     export RESULT_HOME=$(dirname $(jt --use ${VARIANT} graalvm-home))
     cd ${RESULT_HOME}
     mv $(basename $(jt --use ${VARIANT} graalvm-home)) truffleruby-${VARIANT}
     rm -Rf truffleruby-${VARIANT}/legal truffleruby-${VARIANT}/lib/visualvm truffleruby-${VARIANT}/lib/jfr truffleruby-${VARIANT}/tools truffleruby-${VARIANT}/include truffleruby-${VARIANT}/lib/llvm
     tar -I lz4 -cf ${PROJECT_FOLDER}/truffleruby-${VARIANT}.tar.lz4 truffleruby-${VARIANT}

   upload-truffleruby: &UPLOAD_TR |
     sftp tmp-artifacts << EOF
       -mkdir incoming
       -mkdir incoming/${CI_PIPELINE_ID}/
       put ${PROJECT_FOLDER}/truffleruby-${VARIANT}.tar.lz4 incoming/${CI_PIPELINE_ID}/
     EOF
    
   download-variants: &DOWNLOAD_TR |
     [ ! -f ./.gitlab.native-int-only ] && sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/truffleruby-jvm.tar.lz4
     sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/truffleruby-native-libgraal.tar.lz4
  
   install-on-tmpfs: &INSTALL_ON_TMP |
     export PROJECT_FOLDER=$(pwd)
     rm -Rf /tmp/truffleruby
     mkdir -p /tmp/truffleruby
     cp -R faststart /tmp/truffleruby
     cd /tmp/truffleruby
     [ ! -f ${PROJECT_FOLDER}/.gitlab.native-int-only ] && tar -I lz4 -xf ${PROJECT_FOLDER}/truffleruby-jvm.tar.lz4
     tar -I lz4 -xf ${PROJECT_FOLDER}/truffleruby-native-libgraal.tar.lz4

# Build the VMs and run tests
# native includes jvm-ce,
# which is available with the --jvm flag from the laucher
build1-native-and-jvm-ce:
  stage: build
  tags: [yuria]
  script:
    - *GIT_DEPS
    - *PREP_PATH

    # Copy Custom Config into TruffleRuby setup
    - export VARIANT=native-libgraal
    - cp faststart/${VARIANT}.env mx.truffleruby/${VARIANT}

    - jt build --sforceimports --env ${VARIANT}

    - *PACKAGE_TR
    - *UPLOAD_TR
  rules:
    - if: $CI_COMMIT_TAG =~ "/^$/" # don't built for tags, just branches

build2-jvm:
  stage: build
  tags: [yuria2]
  script:
    # try to abort the job if we only try to benchmark native interpreter
    - "[ -f ./.gitlab.native-int-only ] && exit 0"

    - *GIT_DEPS
    - *PREP_PATH
    
    - export VARIANT=jvm
    - jt build --sforceimports --env ${VARIANT}
    
    # Run time: 2.3min
    - jt --use ${VARIANT} test fast
    # Run time: 2sec
    - jt --use ${VARIANT} test :next

    - *PACKAGE_TR
    - *UPLOAD_TR
  rules:
    - if: $CI_COMMIT_TAG =~ "/^$/" # don't built for tags, just branches

# Run Benchmarks
benchmark1:
  stage: benchmark
  tags: [yuria]
  script:
    - *DOWNLOAD_TR
    - *GIT_FASTSTART
    - *INSTALL_ON_TMP
    
    # back to the harddisk so that rebench can read the version details
    - cd ${PROJECT_FOLDER}/faststart
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf profile       m:yuria
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf profile-large m:yuria
    - |
      if [ -f ${PROJECT_FOLDER}/.gitlab.native-int-only ]
      then
        rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf benchmark     m:yuria e:TruffleRuby-native-interp
      else
        rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf benchmark     m:yuria
      fi
    - rm -Rf /tmp/truffleruby
  rules:
      - if: $CI_COMMIT_TAG =~ "/^$/" # don't built for tags, just branches
      - changes:
          - mx.truffleruby/suite.py
          - src/**/*
          - lib/**/*

# Run Benchmarks
benchmark2:
  stage: benchmark
  tags: [yuria2]
  script:
    - *DOWNLOAD_TR
    - *GIT_FASTSTART
    - *INSTALL_ON_TMP
    
    # back to the harddisk so that rebench can read the version details
    - cd ${PROJECT_FOLDER}/faststart
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf benchmark-micros
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf profile       m:yuria2
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf profile-large m:yuria2
    - |
      if [ -f ${PROJECT_FOLDER}/.gitlab.native-int-only ]
      then
        rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf benchmark     m:yuria2 e:TruffleRuby-native-interp
      else
        rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf benchmark     m:yuria2
      fi
    - rm -Rf /tmp/truffleruby
  rules:
      - if: $CI_COMMIT_TAG =~ "/^$/" # don't built for tags, just branches
      - changes:
          - mx.truffleruby/suite.py
          - src/**/*
          - lib/**/*

# Run Benchmarks
benchmark3:
  stage: benchmark
  tags: [yuria3]
  script:
    - *DOWNLOAD_TR
    - *GIT_FASTSTART
    - *INSTALL_ON_TMP
    
    # back to the harddisk so that rebench can read the version details
    - cd ${PROJECT_FOLDER}/faststart
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf profile-micros
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf profile       m:yuria3
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf profile-large m:yuria3
    - |
      if [ -f ${PROJECT_FOLDER}/.gitlab.native-int-only ]
      then
        rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf benchmark     m:yuria3 e:TruffleRuby-native-interp
      else
        rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf benchmark     m:yuria3
      fi
    - rm -Rf /tmp/truffleruby
  rules:
      - if: $CI_COMMIT_TAG =~ "/^$/" # don't built for tags, just branches
      - changes:
          - mx.truffleruby/suite.py
          - src/**/*
          - lib/**/*


report-completion:
  stage: benchmark-completion
  tags: [yuria]
  script:
    - *GIT_FASTSTART
    - cd faststart
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --report-completion rebench.conf
  rules:
      - if: $CI_COMMIT_TAG =~ "/^$/" # don't built for tags, just branches
      - changes:
          - mx.truffleruby/suite.py
          - src/**/*
          - lib/**/*


# A full CI Run, which should be scheduled, weekly or so
full-test-run-on-jvm-ce:on-schedule:
  stage: test
  tags: [yuria3]
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - *GIT_DEPS
    - *PREP_PATH

    - jt build --sforceimports --env jvm-ce
    
    # Run time: 2.3min
    - jt --use jvm-ce test fast

    # Run time: 2sec
    - jt --use jvm-ce test :next
    
    # Run time: 21min
    - jt --use jvm-ce test :truffle
    
    # Run time: 6.6min
    - jt --use jvm-ce test :language
    
    # Run time: 21min
    - jt --use jvm-ce test :core
    
    # Run time: 2.5min
    - jt --use jvm-ce test :library

    # Run time: 2.2min
    - jt --use jvm-ce test :cext

    # Run time: 1min
    - jt --use jvm-ce test :security

    # Run time: 12min
    - jt --use jvm-ce test :command_line
