# This is not real code, we don't maintain strict documentation requirements
Style/Documentation:
  Enabled: false

# Prefer identical code over such rules readabilty rules
Style/GuardClause:
  Enabled: false

Style/UnlessElse:
  Enabled: false

Style/Next:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'harness.rb'
    - 'havlak.rb'
  
Style/HashEachMethods:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'cd.rb'
    - 'json.rb'
    - 'havlak.rb'
    - 'harness.rb'
    - 'harness-rbx.rb'

Metrics/CyclomaticComplexity:
  Enabled: false
  
Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/BlockLength:
  Max: 28

Style/YodaCondition:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/ParameterAlignment:
  Exclude:
    - 'nbody.rb'

Layout/ArgumentAlignment:
  Exclude:
    - 'nbody.rb'

Layout/MultilineOperationIndentation:
  Exclude:
    - 'nbody.rb'

Style/ConditionalAssignment:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'json.rb'

Style/MutableConstant:
  Exclude:
    - 'json.rb'
  
Style/CommentAnnotation:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Lint/Loop:
  Exclude:
    - 'json.rb'

Lint/FloatComparison:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Layout/ExtraSpacing:
  Exclude:
    - 'havlak.rb'
    - 'deltablue.rb'
    - 'cd.rb'
    - 'mandelbrot.rb'
    - 'nbody.rb'

Layout/SpaceAroundOperators:
  Exclude:
    - 'havlak.rb'
    - 'cd.rb'
    - 'mandelbrot.rb'
    - 'nbody.rb'

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/PerlBackrefs:
  Exclude:
    - 'harness.rb'
    - 'harness-rbx.rb'

Naming/FileName:
  Exclude:
    - 'harness-rbx.rb'

Naming/MethodParameterName:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false

Layout/SpaceInsideReferenceBrackets:
  Enabled: false

Style/OrAssignment:
  Enabled: false
